# docker-compose.yml
version: '3.8'

services:
  db:
    env_file: .env
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_ENV: ${VITE_ENV}
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "${CONTAINER_PORT}:80"
    depends_on:
      - db

  bot:
    env_file: .env
    build:
      context: ./backend/aiogram_miniapp
      dockerfile: Dockerfile
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
